-- ############################
-- OpenTriviaOnline Official Schema
--
-- https://opentriviaonline.com
-- https://snowlynxsoftware.net 
--
-- Copyright 2025. SnowLynxSoftware. All Rights Reserved.
-- ############################

-- Trivia Schema. These are all of the tables necessary to run the trivia game.
-- This is the first version of the trivia schema. It will be updated as we add new features.

CREATE TABLE IF NOT EXISTS "trivia_questions" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false,
    "is_published" BOOLEAN DEFAULT false
);