-- ############################
-- OpenTriviaOnline Official Schema
--
-- https://opentriviaonline.com
-- https://snowlynxsoftware.net 
--
-- Copyright 2025. SnowLynxSoftware. All Rights Reserved.
-- ############################

-- Waitlist - Used to store waitlist entries so we can send emails when the site is ready

CREATE TABLE IF NOT EXISTS "waitlist" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "email" TEXT UNIQUE NOT NULL
);