-- ############################
-- OpenTriviaOnline Official Schema
--
-- https://opentriviaonline.com
-- https://snowlynxsoftware.net 
--
-- Copyright 2025. SnowLynxSoftware. All Rights Reserved.
-- ############################

-- AUTH

CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false,
    "email" TEXT UNIQUE NOT NULL,
    "display_name" TEXT NOT NULL,
    "avatar_url" TEXT,
    "profile_text" TEXT,
    "user_type_key" TEXT NOT NULL,
    "is_verified" BOOLEAN DEFAULT false,
    "password_hash" TEXT,
    "last_login" TIMESTAMP,
    "is_banned" BOOLEAN DEFAULT false,
    "ban_reason" TEXT
);

CREATE INDEX IF NOT EXISTS idx_users_email ON "users" ("email");

CREATE TABLE IF NOT EXISTS "user_login_history" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false,
    "user_id" INTEGER
);

ALTER TABLE "user_login_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

-- // USERS
INSERT INTO public.users (email, display_name, user_type_key)
VALUES ('snowlynxsoftware+admin@gmail.com', 'MorpheusZero', 'admin')
ON CONFLICT (id) DO NOTHING;

-- // OAuth Clients
CREATE TABLE IF NOT EXISTS "oauth_clients" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false,
    "client_id" TEXT UNIQUE NOT NULL,
    "client_secret_hash" TEXT NOT NULL,
    "allowed_scopes" JSONB DEFAULT '[]'
);

-- // SETTINGS

CREATE TABLE IF NOT EXISTS "app_settings" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false,
    "allow_registrations" BOOLEAN DEFAULT true,
    "allow_send_emails" BOOLEAN DEFAULT false,
    "is_maintenance_mode" BOOLEAN DEFAULT false,
    "maintenance_mode_message" BOOLEAN DEFAULT false,
    "feature_flags" JSONB DEFAULT '{}'
);