-- ############################
-- OpenTriviaOnline Official Schema
--
-- https://opentriviaonline.com
-- https://snowlynxsoftware.net 
--
-- Copyright 2025. SnowLynxSoftware. All Rights Reserved.
-- ############################

-- Trivia Schema. These are all of the tables necessary to run the trivia game.
-- This is the first version of the trivia schema. It will be updated as we add new features.

CREATE TABLE IF NOT EXISTS "trivia_questions" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false,
    "is_published" BOOLEAN DEFAULT false,
    "question" TEXT NOT NULL,
    "correct_answer" TEXT NOT NULL,
    "tags" TEXT[] NOT NULL
);

CREATE TABLE IF NOT EXISTS "trivia_decks" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "is_approved" BOOLEAN DEFAULT false,
    "is_system_deck" BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS "trivia_deck_questions" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false,
    "deck_id" INTEGER NOT NULL REFERENCES trivia_decks(id) ON DELETE CASCADE,
    "question_id" INTEGER NOT NULL REFERENCES trivia_questions(id) ON DELETE CASCADE,

    UNIQUE(deck_id, question_id) -- Prevent duplicate entries
);

CREATE TABLE IF NOT EXISTS "trivia_game_instances" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false
    "user_id" INTEGER NOT NULL REFERENCES users(id),
    "deck_id" INTEGER NOT NULL REFERENCES trivia_decks(id),
    "started_at" TIMESTAMP DEFAULT (NOW()),
    "ended_at" TIMESTAMP,
    "num_wrong_choices" INTEGER DEFAULT 3,
    "total_correct" INTEGER DEFAULT 0,
    "total_incorrect" INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "trivia_question_attempts" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false,
    "game_instance_id" INTEGER NOT NULL REFERENCES trivia_game_instances(id),
    "question_id" INTEGER NOT NULL REFERENCES trivia_questions(id),
    "picked_answer" TEXT NOT NULL,
    "is_correct" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "wrong_answer_pool" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false,
    "answer_text" TEXT NOT NULL,
    "tags" TEXT[] NOT NULL -- Must match at least one tag from the question to be eligible
);