name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - "hotfix/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to the GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.OTO_PAT }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker build -t ghcr.io/snowlynxsoftware/oto-api/oto-api:$SHORT_SHA .

      # Push the Docker image to the GitHub Container Registry
      - name: Push Docker image
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker push ghcr.io/snowlynxsoftware/oto-api/oto-api:$SHORT_SHA
